/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JSlider;
import javax.xml.bind.DatatypeConverter;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;
import pixelmanipulation_refactor.CustomImage;
import pixelmanipulation_refactor.Filters;
import pixelmanipulation_refactor.MyImage;

/**
 *
 * @author LINK5
 */
public class PixelManipulation extends javax.swing.JFrame {

    /**
     * Creates new form PixelManipulation
     */
    public PixelManipulation() {
        initComponents();
        setLocationRelativeTo(null);
        img = new CustomImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Image1 = new javax.swing.JLabel();
        jButton_SelectImage = new javax.swing.JButton();
        jLabel_Image2 = new javax.swing.JLabel();
        briloo = new javax.swing.JSlider();
        gamma = new javax.swing.JSlider();
        contraste = new javax.swing.JSlider();
        negative = new javax.swing.JRadioButton();
        binarizar = new javax.swing.JRadioButton();
        resetear = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        Avering = new javax.swing.JSlider();
        Gaussian = new javax.swing.JSlider();
        Median = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Image1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Image1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(240, 240, 240)));

        jButton_SelectImage.setText("Sleccionar imágen");
        jButton_SelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelectImageActionPerformed(evt);
            }
        });

        jLabel_Image2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Image2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(240, 240, 240)));
        jLabel_Image2.setOpaque(true);
        jLabel_Image2.setPreferredSize(new java.awt.Dimension(400, 277));

        briloo.setMaximum(10);
        briloo.setMinimum(-10);
        briloo.setMinorTickSpacing(1);
        briloo.setPaintLabels(true);
        briloo.setPaintTicks(true);
        briloo.setSnapToTicks(true);
        briloo.setValue(0);
        briloo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BRILLO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 11))); // NOI18N
        briloo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brilooStateChanged(evt);
            }
        });

        gamma.setMaximum(10);
        gamma.setMinorTickSpacing(1);
        gamma.setPaintLabels(true);
        gamma.setPaintTicks(true);
        gamma.setSnapToTicks(true);
        gamma.setValue(0);
        gamma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GAMMA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 11))); // NOI18N
        gamma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gammaStateChanged(evt);
            }
        });

        contraste.setMaximum(10);
        contraste.setMinimum(-10);
        contraste.setMinorTickSpacing(1);
        contraste.setPaintLabels(true);
        contraste.setPaintTicks(true);
        contraste.setSnapToTicks(true);
        contraste.setValue(0);
        contraste.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTRASTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 11))); // NOI18N
        contraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                contrasteStateChanged(evt);
            }
        });

        negative.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        negative.setText("NEGATIVO");
        negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativeActionPerformed(evt);
            }
        });

        binarizar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        binarizar.setText("BINARIZA");
        binarizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarizarActionPerformed(evt);
            }
        });

        resetear.setText("RESETEAR");
        resetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetearActionPerformed(evt);
            }
        });

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        Avering.setMaximum(10);
        Avering.setMinorTickSpacing(1);
        Avering.setPaintLabels(true);
        Avering.setPaintTicks(true);
        Avering.setSnapToTicks(true);
        Avering.setValue(0);
        Avering.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AVERING", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 11))); // NOI18N
        Avering.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AveringStateChanged(evt);
            }
        });

        Gaussian.setMaximum(10);
        Gaussian.setMinorTickSpacing(1);
        Gaussian.setPaintLabels(true);
        Gaussian.setPaintTicks(true);
        Gaussian.setSnapToTicks(true);
        Gaussian.setValue(0);
        Gaussian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GAUSSIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 11))); // NOI18N
        Gaussian.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GaussianStateChanged(evt);
            }
        });

        Median.setMaximum(10);
        Median.setMinorTickSpacing(1);
        Median.setPaintLabels(true);
        Median.setPaintTicks(true);
        Median.setSnapToTicks(true);
        Median.setValue(0);
        Median.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MEDIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 11))); // NOI18N
        Median.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MedianStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(briloo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(negative)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(binarizar)
                        .addGap(81, 81, 81)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel_Image2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Gaussian, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Avering, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Median, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resetear)
                                .addGap(86, 86, 86)
                                .addComponent(guardar)
                                .addGap(63, 63, 63)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton_SelectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_SelectImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Image2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(briloo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contraste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Avering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gaussian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Median, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(negative)
                    .addComponent(binarizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetear)
                    .addComponent(guardar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String link;
    private void jButton_SelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelectImageActionPerformed
        // TODO add your handling code here:
        Image imageToShow;

        String direccion = img.getImage().getPath();
        Mat newImage = Imgcodecs.imread(direccion);
        link = direccion;

        myImage = newImage;

        buffer = img.toBytes(myImage);

        imageToShow = img.toImage(myImage, buffer);

        jLabel_Image1.setIcon(new ImageIcon(imageToShow.getScaledInstance(this.jLabel_Image1.getWidth(), this.jLabel_Image1.getHeight(), Image.SCALE_DEFAULT)));

        brightImage = myImage;


    }//GEN-LAST:event_jButton_SelectImageActionPerformed

    int actual = 0;
    int previo = 0;

    private void brilooStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brilooStateChanged
        // TODO add your handling code here:
        Mat imagen = myImage;
        JSlider source = (JSlider) evt.getSource();
        byte[] buffer = img.toBytes(imagen);
        // byte[] bufferTemp =img.toBytes(temporalImage);

        actual = source.getValue();

        if (actual > previo) {
            imagen = Filters.addBrightness(buffer, imagen, actual);
            //System.out.println("El previo es: "+previo+"   y el actual es "+actual);
            previo = actual;

        }
        if (actual < previo) {

            imagen = Filters.lessBrightness(buffer, imagen, actual);
            //System.out.println("El previo es: "+previo+"   y el actual es "+actual);
            previo = actual;

        }
        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));

    }//GEN-LAST:event_brilooStateChanged

    private void gammaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gammaStateChanged
        // TODO add your handling code here:
        Mat imagen = myImage;
        JSlider source = (JSlider) evt.getSource();
        byte[] buffer = img.toBytes(imagen);
        // byte[] buffer = img.toBytes(brightImage);       
        float valor = source.getValue();

        valor = valor / 10;
        imagen = Filters.correccionGamma(imagen, valor);

        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));

    }//GEN-LAST:event_gammaStateChanged
    int previoContraste = 0, actualContraste = 0;

    private void contrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_contrasteStateChanged
        // TODO add your handling code here:
        Mat imagen = myImage;
        JSlider source = (JSlider) evt.getSource();

        // byte[] bufferTemp =img.toBytes(temporalImage);
        actualContraste = source.getValue();

        /*  if (actualContraste < 0) {
            actualContraste = actualContraste * (-1);
        }*/
        if (actualContraste > previoContraste) {

            imagen = Filters.addcorreccionContraste(imagen, actualContraste);
            previoContraste = actualContraste;

        }
        if (actualContraste < previoContraste) {

            imagen = Filters.lesscorreccionContraste(imagen, actualContraste);
            previoContraste = actualContraste;

        }

        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));

    }//GEN-LAST:event_contrasteStateChanged
    int n = 0;
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        Mat imagen = myImage;
        CustomImage ci = new CustomImage();
        n++;
        ci.guardarImg(imagen, n);
    }//GEN-LAST:event_guardarActionPerformed

    private void resetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetearActionPerformed

        // TODO add your handling code here:
        Image imageToShow;
        Mat newImage = Imgcodecs.imread(link);

        myImage = newImage;

        buffer = img.toBytes(myImage);

        imageToShow = img.toImage(myImage, buffer);

        jLabel_Image2.setIcon(new ImageIcon(imageToShow.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));

        brightImage = myImage;

        gamma.setValue(0);
        briloo.setValue(0);
        contraste.setValue(0);
        Avering.setValue(0);
        prevAver = 0;
        Gaussian.setValue(0);
        prevGaus = 0;
        Median.setValue(0);
        prevMedia = 0;


    }//GEN-LAST:event_resetearActionPerformed

    private void negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativeActionPerformed
        // TODO add your handling code here:
        Mat imagen = myImage;

        imagen = Filters.negativo(imagen);

        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));

    }//GEN-LAST:event_negativeActionPerformed

    private void binarizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarizarActionPerformed
        // TODO add your handling code here:
        if (binarizar.isSelected()) {
            Mat imagen = myImage;
            imagen = Filters.binarizacion(imagen);
            Image image = img.toImage(imagen, buffer);
            jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));
        } else {
            Image imageToShow;
            Mat newImage = Imgcodecs.imread(link);
            myImage = newImage;
            buffer = img.toBytes(myImage);
            imageToShow = img.toImage(myImage, buffer);
            jLabel_Image2.setIcon(new ImageIcon(imageToShow.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));
            brightImage = myImage;
        }

    }//GEN-LAST:event_binarizarActionPerformed
    int actualAver = 0, prevAver = 0;
    private void AveringStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AveringStateChanged

        Mat imagen = myImage;
        JSlider source = (JSlider) evt.getSource();
        double[] resultado;
        // byte[] bufferTemp =img.toBytes(temporalImage);
        actualAver = source.getValue();

        
        
        if (actualAver > prevAver) {

            for (int i = 0; i < imagen.rows() - 2; i++) {
                for (int j = 0; j < imagen.cols() - 2; j++) {

                    resultado = Filters.avering(imagen, i, j);

                    imagen.put(i + 1, j + 1, resultado);
                }
            }
            prevAver = actualAver;
        }
        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));
        
    }//GEN-LAST:event_AveringStateChanged
    int prevGaus = 0, actGaus = 0;
    private void GaussianStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GaussianStateChanged
        // TODO add your handling code here:
        Mat imagen = myImage;
        JSlider source = (JSlider) evt.getSource();
        double[] resultado;
        // byte[] bufferTemp =img.toBytes(temporalImage);
        actGaus = source.getValue();

        
        
        if (actGaus > prevGaus) {

            for (int i = 0; i < imagen.rows() - 2; i++) {
                for (int j = 0; j < imagen.cols() - 2; j++) {

                    resultado = Filters.gaussian(imagen, i, j);

                    imagen.put(i + 1, j + 1, resultado);
                }
            }
            prevGaus = actGaus;
        }
        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));
        
    }//GEN-LAST:event_GaussianStateChanged
    int prevMedia = 0, actMedia = 0;
    private void MedianStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MedianStateChanged
        // TODO add your handling code here:
        Mat imagen = myImage;
        JSlider source = (JSlider) evt.getSource();
        double[] resultado;
        // byte[] bufferTemp =img.toBytes(temporalImage);
        actMedia = source.getValue();

        
        
        if (actMedia > prevMedia) {

            for (int i = 0; i < imagen.rows() - 2; i++) {
                for (int j = 0; j < imagen.cols() - 2; j++) {

                    resultado = Filters.media(imagen, i, j);

                    imagen.put(i + 1, j + 1, resultado);
                }
            }
            prevMedia = actMedia;
        }
        Image image = img.toImage(imagen, buffer);
        jLabel_Image2.setIcon(new ImageIcon(image.getScaledInstance(this.jLabel_Image2.getWidth(), this.jLabel_Image2.getHeight(), Image.SCALE_DEFAULT)));
        
    }//GEN-LAST:event_MedianStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PixelManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PixelManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PixelManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PixelManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PixelManipulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Avering;
    private javax.swing.JSlider Gaussian;
    private javax.swing.JSlider Median;
    private javax.swing.JRadioButton binarizar;
    private javax.swing.JSlider briloo;
    private javax.swing.JSlider contraste;
    private javax.swing.JSlider gamma;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton_SelectImage;
    private javax.swing.JLabel jLabel_Image1;
    private javax.swing.JLabel jLabel_Image2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton negative;
    private javax.swing.JButton resetear;
    // End of variables declaration//GEN-END:variables
    private Mat myImage;
    private byte[] buffer;
    private CustomImage img;
    private Mat brightImage;

}
